original_list = [64, 34, 25, 12, 22, 11, 90]
print("Original list:", original_list)
original_list.sort()
print("Sorted list:", original_list)
original_list = sorted(original_list)
print("Sorted list using sorted():", original_list)
original_list.append(100)
print("List after appending 100:", original_list)
original_list.remove(12)
print("List after removing 12:", original_list)
original_list.remove(original_list[0])
print("List after removing the first element:", original_list)
original_list.insert(0, 55)
print("List after inserting 55 at index 0:", original_list)
original_list.reverse()
print("List after reversing:", original_list)
